#This layout inspired by popular economy games
topTitle:
  x: 90
  y: 90
  width: 635
  height: 50
  align: center
  
bottomTitle:
  x: 90
  y: 300
  width: 635
  height: 50
  align: center

art:
  x: 75
  y: 150
  width: 675
  height: 520

topRules:
  x: 100
  y: 125
  width: 625
  height: 275
  valign: middle
  align: center
  font_size: 6
  
bottomRules:
  x: 100
  y: 335
  width: 625
  height: 275
  valign: middle
  align: center
  font_size: 6

type:
  x: 90
  y: 955
  width: 645
  height: 50
  align: center

lower_right:
  x: 675
  y: 975
  width: 75
  height: 75
  font_size: 6
  valign: bottom
  align: right
lr: #alias
  extends: lower_right

lower_left:
  x: 75
  y: 975
  width: 75
  height: 75
  font_size: 6
  valign: bottom
  align: left
ll: # alias
  extends: lower_left

copyright:
  x: 75
  y: 1025
  width: 675
  height: 25
  font_size: 5
  align: center
  valign: bottom
#aliases for copyright
copy:
  extends: copyright
credit:
  extends: copyright
credits:
  extends: copyright

# The "cut line", without rounded corners
cut:
  x: 37.5
  y: 37.5
  width: 750
  height: 1050

# The "safe zone" as defined by TheGameCrafter poker cards
safe:
  x: 75
  y: 75
  width: 675
  height: 975
  radius: 16
  dash: 3 3